### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by ys634** [ys634/Travel-Expense-YS#1]
**Higher Priority**

Overall:

- [ ] Add more units
- [ ] Include conversions

EntryFragment:

- [ ] Keep parameters after jumping to countries and units.
- [ ] Make card view clickable
- [ ] Show error messages when date is out of the trip duration

TransactionListFragment

- [ ] Make it sectioned by dates

StatsFragment

- [ ] Format pie chart
- [ ] Format bar chart
- [ ] Show calculations when stats are clicked

Categories

- [ ] Make it draggable
- [ ] Show edit icon when category is selected

TripsActivity

- [ ] Editing a trip info doesn't reflect
- [ ] When deleting a trip, the trip order gets messed up

**Lower priority**

CountriesActivity

- [ ] Add flags
